feat: create initial game
UNOGroup-Practicum/uno-game pull request #13
Opened 2023-03-01 12:22 UTC by AleksandrMenshchikov

### Создание старта игры

2023-03-01 14:28 UTC, cap-Bernardito reviewed
Здорово. Хорошее начало ))
Немного комментов по коду оставил.

2023-03-01 14:28 UTC, cap-Bernardito commented on packages/client/src/components/app/App.tsx
Думаю, стоит использовать константу
```js
{location.pathname !== routes.game.path && <AppHeader />}
```

2023-03-01 14:28 UTC, cap-Bernardito commented on packages/client/src/components/game/Game.test.tsx
> +});
Тут TS ругается. Нужно `export {}` добавить в конец файла.

2023-03-01 14:28 UTC, cap-Bernardito commented on packages/client/src/components/game/Game.tsx
> +    canvas.width = window.innerWidth;
Если указать дженерик для useRef, можно убрать `as unknown`
```js
  const ref = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = ref.current as HTMLCanvasElement;
```

2023-03-01 14:28 UTC, cap-Bernardito commented on packages/client/src/components/game/Game.tsx
> +              setCardsAmountForGamer(
Привычнее видеть
```js
if (typeof idx !== "undefined") {
```
Вот например в lodash как [пишут](https://github.com/lodash/lodash/search?q=typeof)
Но я не наставиваю ))

2023-03-01 14:28 UTC, cap-Bernardito commented on packages/client/src/components/game/Game.tsx
> +          ((canvas.width / 2 - 40 - xEndPoint) / (canvas.height / 2 - 90 - yEndPoint)) * rate;
Есть предложение разделять строкой объявление переменных и функции. А то сложно читать единое полотно ))
```js
const a = 1;
let b = 3;

function atata(){}
```

2023-03-01 14:28 UTC, cap-Bernardito commented on packages/client/src/components/game/Game.tsx
> +              setCardsAmountForGamer(
Ну и if-ы тоже отделять друг от друга. Приятнее читать.
```js
const idx = generator.next().value as number;

if (idx !== undefined) {
  cardsDistribution(gamersPositions[idx].cards[0], gamersPositions[idx].cards[1]);
}

if (idx === undefined) {
```
Но кому как возможно ))

2023-03-01 14:28 UTC, cap-Bernardito commented on packages/client/src/components/game/Game.tsx
> +export default memo(Game);
`React.memo` тут не нужен я думаю, т.к. он чекает, изменились ли пропсы, а у компонента `Game` нет пропсов.

Ну и есть предложение пользоваться именованными импортами, т.к. с ними проще работать. [Один из аргументов](https://medium.com/devschacht/%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D1%8F-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%82%D0%B0%D0%BB-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%8D%D0%BA%D1%81%D0%BF%D0%BE%D1%80%D1%82-%D0%BF%D0%BE-%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E-%D0%B2-%D0%BC%D0%BE%D0%B8%D1%85-javascript-%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8F%D1%85-d03e63bed126)

2023-03-01 15:01 UTC, AleksandrMenshchikov commented on packages/client/src/components/app/App.tsx
Исправил.

2023-03-01 15:05 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/Game.tsx
> +    canvas.width = window.innerWidth;
Исправил.

2023-03-01 15:34 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/Game.tsx
> +              setCardsAmountForGamer(
Исправил.

2023-03-01 15:38 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/Game.tsx
> +          ((canvas.width / 2 - 40 - xEndPoint) / (canvas.height / 2 - 90 - yEndPoint)) * rate;
Хорошо.

2023-03-01 15:41 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/Game.tsx
> +              setCardsAmountForGamer(
Хорошо, попробую так писать.

2023-03-01 15:58 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/Game.tsx
> +export default memo(Game);
React.memo лучше оставить, компонент срабатывает в случаях изменения props, state и автоматически срабатывает вслед за родителем, если в App props, state или hook сработает потянет за собой детей.

2023-03-01 17:21 UTC, Olegas commented on packages/client/src/components/game/utils/createGamersPositions.ts
> +  function createGamerImage(x: number, y: number) {
Добавить бы пустых строк между функциями - сложно читается...

2023-03-01 17:26 UTC, Olegas commented on packages/client/src/components/game/utils/createGamersPositions.ts
> +  }
Очень страшная функция (
Нельзя ли ее циклом оформить? И все расчеты вычислить от номера шага?

2023-03-01 17:28 UTC, Olegas commented on packages/client/src/components/game/Game.tsx
> +          if (shuffleArrayCards[index].owner.toLowerCase() === gamersList[0].name.toLowerCase()) {
А для его кейс строк менять? Как может быть что он тут разный?

2023-03-01 17:31 UTC, Olegas commented on packages/client/src/components/game/Game.tsx
> +        createBackSideCard(ctx, canvas.width / 2 - 40, canvas.height / 2 - 60);
canvas.width / 2 - 40
canvas.height / 2 - 60 
и т.п. 
очень много копипасты с одними и теми же значениями. Их бы в переменные венести

2023-03-01 17:35 UTC, Olegas commented on packages/client/src/components/game/Game.tsx
> +    function cardsDistribution(xEndPoint: number, yEndPoint: number) {
А нельзя вот эти все многочисленные функции вынести из компонента что бы сделать их чистыми и не создавать каждый запуск новые (увеличивая тем самым нагрузку на Garbage Collector)? Так и читаться будет получше. Сложно читать такое полотно...

2023-03-01 17:36 UTC, Olegas requested changes
Сложно читается (

2023-03-01 19:07 UTC, cap-Bernardito approved these changes

2023-03-01 19:37 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/utils/createGamersPositions.ts
> +  }
Исправил.

2023-03-01 19:38 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/utils/createGamersPositions.ts
> +  function createGamerImage(x: number, y: number) {
Исправил.

2023-03-01 19:43 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/Game.tsx
> +          if (shuffleArrayCards[index].owner.toLowerCase() === gamersList[0].name.toLowerCase()) {
Исправил.

2023-03-01 20:40 UTC, KozlovAleksandr approved these changes

2023-03-02 08:56 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/Game.tsx
> +        createBackSideCard(ctx, canvas.width / 2 - 40, canvas.height / 2 - 60);
Исправил.

2023-03-02 15:44 UTC, Olegas requested changes

2023-03-02 15:44 UTC, Olegas commented on packages/client/src/components/game/Game.tsx
> +            createBackSideCard(ctx, point.x - 40, point.y - 60);
Вот эти point.x - 40, point.y - 60 - опять много копипасты с ними, через всю функцию использование...

2023-03-02 15:44 UTC, Olegas commented on packages/client/src/components/game/utils/createGamersPositions.ts
> +  }
Огонь! 🔥

2023-03-02 15:44 UTC, Olegas commented on packages/client/src/components/game/utils/createGamersPositions.ts
> +  }
Но вообще enum тут - несколько странное решение. Enum обычно используется для группировки взаимоисключающих значений - например цвета или какие-то состояния. А тут скорее всего подошли бы просто две константы с понятными именами

2023-03-02 15:44 UTC, Olegas commented on packages/client/src/components/game/utils/createUserCards.ts
> +          shuffleArrayCards[index].owner.toLowerCase() === gamersList[0].name.toLowerCase() &&
Тут снова сравнение с преобразованием кейса. Нужно ли оно?

2023-03-02 16:13 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/utils/createGamersPositions.ts
> +  }
enum заменил на обычный объект

2023-03-02 16:21 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/Game.tsx
> +            createBackSideCard(ctx, point.x - 40, point.y - 60);
Исправил.

2023-03-02 16:25 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/utils/createUserCards.ts
> +          shuffleArrayCards[index].owner.toLowerCase() === gamersList[0].name.toLowerCase() &&
Исправил.

2023-03-03 16:02 UTC, Olegas approved these changes

2023-03-03 16:19 UTC, merged