feat(23UG-63): Реализует функции для работы с запросами
UNOGroup-Practicum/uno-game pull request #16
Opened 2023-03-03 18:01 UTC by cap-Bernardito

### Какую задачу решаем

2023-03-03 18:44 UTC, AleksandrMenshchikov approved these changes

2023-03-04 05:42 UTC, Olegas approved these changes

2023-03-04 05:43 UTC, Olegas requested changes

2023-03-04 05:43 UTC, Olegas commented on packages/client/src/services/api/types.d.ts
> +export type APIError = {
А зачем .d.ts? Эти файлы обычно руками не пишут а генерируются ts-компилятором при подготовке библиотеки (что бы не потерять тайпинги).

2023-03-04 08:07 UTC, cap-Bernardito commented on packages/client/src/services/api/types.d.ts
> +export type APIError = {
У меня следующие доводы:
1. У нас же не модуль, мы не будем его публиковать в npm, не будем подготавливать и экспортировать типы для него.
2. Для собранного в `prod` режиме js файла типы нам тоже не нужны, т.к. он только для деплоя нужен - работать с минифицированным кодом никто не будет.
3. Перечитал раздел про [dts](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) и выяснил следующее. Да, `d.ts` файлы обсуждаются по большей части как средство для типизации js кода библиотек. Но не нашел там запрета на использование в проекте с TS и ручного написания.
4. Мне удобно экспортировать глобально namespace для частоиспользуемых типов в проекте, чтобы не импортировать их в каждом файле, где они понадобятся. Тут пока не такой случай, но позднее, если много где пригодится тип, допускал такую возможность.
5. Т.о., даже если я использую файлы `d.ts` не совсем по назначению, то критичного в этом ничего не вижу.

У меня не большой опыт работы с TS, и очень-очень может быть, что я не прав и не надо так делать. Но до сих пор, никто мне на эту ошибку не указывал, а потому и не ведаю, что творю ))

Получается, мы должны по большей части избегать использования файлов d.ts в TS-проектах?

2023-03-04 15:10 UTC, EAbashin approved these changes

2023-03-04 17:35 UTC, Olegas commented on packages/client/src/services/api/types.d.ts
> +export type APIError = {
Да, действительно, запрета нет, но...
Объясню почему я против такого способа.
 1. Глобальные типы скрывают зависимости. Они делают их неявными. Я за явное вместо неявного.
 2. Глобальные типы сложно читать. Я за то, что бы типы были там где они появились. Если это пропсы компонента пусть они будут в файле компонента, тогда файл сильно проще читается - не надо прыгать по проекту и искать типы (особенно удобно это когда делаешь ревью онлайн в GitHub и т.п.)


> никто мне на эту ошибку не указывал, а потому и не ведаю, что творю ))

Это не ошибка. Скорее это практика, которая дает странные результаты. Я не настаиваю. Если например вы с командой решите что вам так удобнее - ок. 

Я тут хочу лишь обратить внимание на то, что на мой взгляд изначально это механизм не для этой цели. И его использование дает сайд-эффекты, которые влияют на проект.

2023-03-05 10:25 UTC, cap-Bernardito commented on packages/client/src/services/api/types.d.ts
> +export type APIError = {
> Я тут хочу лишь обратить внимание на то, что на мой взгляд изначально это механизм не для этой цели...

Здорово, что вы обратили на это внимание. Ваши аргументы звучат разумно, спасибо за пояснение, теперь буду знать и пользоваться ))

2023-03-05 13:30 UTC, Olegas approved these changes

2023-03-05 14:01 UTC, merged