feat(23UG-64): реализует аутентификацию пользователя
UNOGroup-Practicum/uno-game pull request #17
Opened 2023-03-04 11:46 UTC by cap-Bernardito

### Какую задачу решаем

- добавлены запросы для аутентификации, логина и логаута
- подключен store
- реализовано получение и сохранение в store статуса аутентификации пользователя

2023-03-04 13:29 UTC, AleksandrMenshchikov approved these changes

2023-03-04 15:41 UTC, EAbashin approved these changes

2023-03-04 17:44 UTC, Olegas requested changes

2023-03-04 17:44 UTC, Olegas commented on packages/client/src/services/api/authApi.ts
> +  me: async (): Promise<User | APIError> => {
Расскажите, в чем идея, превращать ошибку в нормальный ответ но с признаком ошибки? Почему просто не использовать await/catch в точках вызова, если нужно отловить ошибку, и не добавлять дополнительную утилиту для проверки?

Необычная для меня практика. Хочу узнать мотивацию за ней.

2023-03-04 17:44 UTC, Olegas commented on packages/client/src/services/slices/auth-slice.ts
> +    dispatch(setStatus(EAuthStatus.no));
Вот последствия того, что вы "скрыли" ошибку. Теперь вместо asyncThunk и готовых actions вида pending/success/failure вам придется проверять руками

2023-03-04 17:44 UTC, Olegas commented on packages/client/src/services/slices/auth-slice.ts
> +  dispatch(setStatus(EAuthStatus.ok));
А для чего два действия тут? Такая комбинация делает возможной состояние "успешный ответ но неуспешный статус"

2023-03-05 10:28 UTC, cap-Bernardito commented on packages/client/src/services/api/authApi.ts
> +  me: async (): Promise<User | APIError> => {
Идея была в том, чтобы нормализовать сообщение об ошибке в 1 месте, и в разных файлах не обрабатывать ее. Но согласен, что неумная это мысль ))
Меня смущало то, что разные инструменты (fetch, axios,...) по-разному работают с ошибками. Fetch, например 400 и 500 ошибки не выбрасывает. А поведение класса с запросами хотелось сделать не зависящим от инструмента, запросы отправляющего (если вдруг HTTP-клиент сменится, то на бизнес логике это не должно отразиться).

Но я не по тому пути пошел. Надо было определиться с поведением реквестера, ошибки с какими кодами выбрасываем, и т.д., и настраивать HTTP-клиент в соответствии с этим поведением.
А так получилась ерунда - и стектрейс не видно, и часть программ, рассчитывающая на определенное поведение запросов, не работает.

Переделал.

2023-03-05 10:34 UTC, cap-Bernardito commented on packages/client/src/services/slices/auth-slice.ts
> +    dispatch(setStatus(EAuthStatus.no));
На самом деле, я тут все равно не собирался использовать готовые `actions`. Просто вместо `if(apiHasError(response)){` был бы `try catch`.

Но раз вы указали на это, то вероятно, делать через готовые экшоны - хорошая практика.
Спасибо за наводку, переписал ))

2023-03-05 10:39 UTC, cap-Bernardito commented on packages/client/src/services/slices/auth-slice.ts
> +  dispatch(setStatus(EAuthStatus.ok));
Моя ошибка.
Цель была такая - при первом заходе на сайт нужно сделать один запрос для аутентификации и чтобы потом он не повторялся при изменении состояния пользователя.
Но этого можно добиться проще
```js
useEffect(()=>{}, [])
```
Избавился от поля `статус` в стейте.

2023-03-05 13:29 UTC, Olegas approved these changes

2023-03-05 14:08 UTC, merged

2023-03-05 14:20 UTC, Olegas commented on packages/client/src/services/api/authApi.ts
> +  me: async (): Promise<User | APIError> => {
> Меня смущало то, что разные инструменты (fetch, axios,...) по-разному работают с ошибками

Это кстати очень правильный вопрос. Очень круто что ты его задаешь и ищешь пути 👍