feat: добавляет валидацию для форм
UNOGroup-Practicum/uno-game pull request #21
Opened 2023-03-05 19:08 UTC by MakhovRoman

### Какую задачу решаем

- добавлена валидация для инпутов и форм
- логика валидации вынесена в отдельный хелпер

2023-03-05 20:13 UTC, EAbashin approved these changes

2023-03-05 20:49 UTC, cap-Bernardito requested changes
Подскажи, на какое событие ты валидацию задумывал? Просто как-то странно работает - при первом заходе на страницу на `onchage` не работает, но после того, как нажмешь `отправить`, начинает работать на `onchage`. Нужно исчинить эту историю.

2023-03-05 20:49 UTC, cap-Bernardito commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +import { useForm, Controller, SubmitHandler, useFormState } from "react-hook-form";
Если новая библиотека появилась в проекте, то должны были поменяться файлы `package.json` и `yarn.lock`.

2023-03-05 20:49 UTC, cap-Bernardito commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +  const { errors } = useFormState({ control });
Мне кажется `useFormState` можно удалить, а ошибки из `useForm` брать

```js
  const {
    control,
    handleSubmit,
    formState: { errors, isValid },
  } = useForm({
    defaultValues: {
      login: "",
      password: "",
    },
  });
```
Ну и кнопку отправки формы на основании ключа `isValid` включать/отключать

2023-03-05 20:49 UTC, cap-Bernardito commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +                  onChange={(event) => field.onChange(event)}
Можно укоротить `onChange={field.onChange}`

2023-03-05 20:49 UTC, cap-Bernardito commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +};
А в каком случае при логине пароля может не быть?
Поле же `password` обязательное.

2023-03-05 20:49 UTC, cap-Bernardito commented on packages/client/src/pages/LoginPage/LoginPage.tsx
>  import styles from "./LoginPage.module.scss";
Пока страницу логина делаешь, добавь заодно в ксс отступ сверху снизу, как на странице регистрации
```scss
.root {
  ...
  margin: 6rem 0;
}
```

2023-03-05 20:53 UTC, cap-Bernardito commented on packages/client/src/pages/RegisterPage/RegisterPage.tsx
> +};
А зачем здесь дженерик? Он как-то странно выглядит - получается у всех полей формы всегда один тип?
На странице логина такой тип
```ts
type TFormInput = {
  login: string;
  password?: string;
};
```
а тут почему другой?

2023-03-06 09:31 UTC, MakhovRoman commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +import { useForm, Controller, SubmitHandler, useFormState } from "react-hook-form";
Переустановил зависимости.

2023-03-06 09:31 UTC, MakhovRoman commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +  const { errors } = useFormState({ control });
Поправил.

2023-03-06 09:31 UTC, MakhovRoman commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +                  onChange={(event) => field.onChange(event)}
Поправил.

2023-03-06 09:32 UTC, MakhovRoman commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +};
Поправил.

2023-03-06 09:33 UTC, MakhovRoman commented on packages/client/src/pages/LoginPage/LoginPage.tsx
>  import styles from "./LoginPage.module.scss";
Добавил.

2023-03-06 09:34 UTC, MakhovRoman commented on packages/client/src/pages/RegisterPage/RegisterPage.tsx
> +};
Дженерик добавил, чтобы не писать на каждому полю ```string```. Привел ```type``` к единому виду.

2023-03-06 09:38 UTC, MakhovRoman commented
Я валидацию оставил стандартную, которая шла из коробки ```react-hook-form``` - при вводе значения до срабатывания ```submit``` сообщения об ошибках не появляются. Поправил код - ```helplerText``` появляется при первом вводе.

2023-03-06 10:08 UTC, cap-Bernardito commented on packages/client/src/pages/RegisterPage/RegisterPage.tsx
> +};
Почему `confirm_password` опциональное поле?

Насколько я могу судить, этот тип используется только тут
```ts
 const onSubmit: SubmitHandler<TFormInput> = (data) => {
    const result = { ...data };
    delete result.confirm_password;
    console.log(result);
  };
```
и сюда приходят все поля формы, в т.ч. и `confirm_password`. В каком случае его может не быть?

2023-03-06 10:11 UTC, cap-Bernardito commented on packages/client/src/pages/RegisterPage/RegisterPage.tsx
> +  };
Не очень мне нравится, что создается новый объект и из него потом поле удаляется. Логичнее на этапе создания включить в него только нужные поля.

```js
  const onSubmit: SubmitHandler<TFormInput> = (data) => {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const {confirm_password, ...result} = { ...data };

    console.log(result);
  };
```

2023-03-06 10:59 UTC, MakhovRoman commented on packages/client/src/pages/RegisterPage/RegisterPage.tsx
> +};
Опциональным сделал поле, т.к. TS ругался в процессе создания нового объекта и исключения из него свойства ```confirm_password```. Проблема решена в комментарии ниже)

2023-03-06 10:59 UTC, MakhovRoman commented on packages/client/src/pages/RegisterPage/RegisterPage.tsx
> +  };
Не додумался до такого хода)

2023-03-06 12:31 UTC, cap-Bernardito approved these changes
Есть еще предложение папку `helpers` в `utils`  переименовать. А так, выглядит нормально.

2023-03-06 16:58 UTC, Olegas approved these changes

2023-03-06 19:05 UTC, AleksandrMenshchikov approved these changes

2023-03-07 08:25 UTC, KozlovAleksandr approved these changes

2023-03-07 11:13 UTC, merged