dev-game-v1
UNOGroup-Practicum/uno-game pull request #26
Opened 2023-03-11 18:15 UTC by AleksandrMenshchikov

### Создание игры Соло (robot vs user)

2023-03-12 10:09 UTC, EAbashin approved these changes

2023-03-12 19:09 UTC, Olegas commented
Смотрю...

2023-03-13 18:22 UTC, Olegas requested changes

2023-03-15 15:59 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/types/typeAliases.ts
> +  cards: [number, number, string];
Отредактировал строку 32.
gamersPositions: TGamersPositions

2023-03-15 16:00 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/utils/createCanvasCenter.ts
> +    //createLeftDirection(ctx, canvas.width / 2 - 200, canvas.height / 2 - 60);
Комментарии убрал.

2023-03-15 16:00 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/utils/createUserCardsWithCoordinates.ts
> +          xRight: coord.x - (rate / 2 - 60),
Отрефакторил.

2023-03-15 20:04 UTC, Olegas requested changes

2023-03-15 20:04 UTC, Olegas commented on packages/client/src/components/game/utils/handleUserClick.ts
> +          ctx?.clearRect(gamersPositions[0].name[0], gamersPositions[0].name[1] - 20, 120, 25);
Зачем доступ с проверкой? Как может быть что вы во всю обрабатываете клики пользователя, а контекста у вас нет?

2023-03-15 20:04 UTC, Olegas commented on packages/client/src/components/game/utils/signalizeName.ts
> +): [NodeJS.Timer, NodeJS.Timer] {
Неправильный тип. Текущее окружение явно не NodeJS а браузер. Если нужен тип таймера, попробуйте заюзать ReturnType<typeof setInterval> или может просто number подойдет?

2023-03-17 14:02 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/utils/signalizeName.ts
> +): [NodeJS.Timer, NodeJS.Timer] {
Исправил.

2023-03-17 14:03 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/utils/handleUserClick.ts
> +          ctx?.clearRect(gamersPositions[0].name[0], gamersPositions[0].name[1] - 20, 120, 25);
Исправил.

2023-03-17 14:03 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/utils/handleUserClick.ts
> +        copiedShuffleArrayCards && setShuffleArrayCards(copiedShuffleArrayCards);
Исправил.

2023-03-17 14:03 UTC, AleksandrMenshchikov commented on packages/client/src/components/game/utils/handleUserClick.ts
> +        const copiedShuffleArrayCards = shuffleArrayCards?.map((item) => {
Исправил.

2023-03-18 07:07 UTC, Olegas approved these changes

2023-03-18 07:50 UTC, merged