feat(23UG-3): реализует вёрстку страницы Профиль
UNOGroup-Practicum/uno-game pull request #27
Opened 2023-03-12 10:12 UTC by EAbashin

2023-03-12 12:25 UTC, cap-Bernardito requested changes

2023-03-12 12:25 UTC, cap-Bernardito commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +import { currentUserData } from "../ForumPage/data/data";
[Тут](https://github.com/UNOGroup-Practicum/uno-game/pull/24) добавлена возможность писать импорты без точек для основных папок и автосортировка. Давай без точек писать.
```ts
import { InputNames, validationTemplate } from "utils/validation/validation";
import React, { useEffect, useState } from "react";
import { currentUserData } from "pages/ForumPage/data/data";
```
так понятнее откуда что импортируется и они должны отсортироваться при коммите (если нет, то `yarn format` сделает это).

2023-03-12 12:25 UTC, cap-Bernardito commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +import changeAvatar from "../../../public/change-avatar.png";
У нас же есть уже иконки в [mui](https://mui.com/material-ui/material-icons/?query=image) - давай оттуда возмем. Вот [пример использования](https://github.com/UNOGroup-Practicum/uno-game/blob/dev/packages/client/src/components/app-header/AppHeader.tsx#L1). Или есть причина именно эту использовать? ))

2023-03-12 12:25 UTC, cap-Bernardito commented on packages/client/src/pages/ProfilePage/ProfilePage.module.scss
> +      }
Аватар круглый, а при наведении квадратный оверлей появляется. На вкус и цвет друг нет конечно, но может на круглом сторгуемся? )) Выглядит странно. Но тут, как народ решит, я не наставиваю ))

2023-03-12 12:51 UTC, AleksandrMenshchikov approved these changes

2023-03-12 19:12 UTC, EAbashin commented on packages/client/src/components/app/App.tsx
> +
Если запускать не весь проект, а только client, то базовый URL не определяется и запросы приходят на http://localhost:3000/
Вот здесь:
const axiosInstance = axios.create({
  baseURL: import.meta.env.VITE_API_ENDPOINT,
  withCredentials: true,
});
Я этого не знал и думал, что авторизация не работает, поэтому переместил временно Route с которым работал. Уже вернул обратно.

2023-03-12 19:14 UTC, EAbashin commented on packages/client/src/pages/ForumPage/ForumMessagesListPage.tsx
>              <Button onClick={delTheme} variant="outlined" color="error" startIcon={<DeleteIcon />}>
Переделал. Теперь беру данные из стора.

2023-03-12 19:15 UTC, EAbashin commented on packages/client/src/pages/ForumPage/data/data.ts
> +      display_name: "Евгений",
Ок

2023-03-12 19:15 UTC, EAbashin commented on packages/client/src/pages/ForumPage/types/types.ts
>  };
ОК

2023-03-12 19:17 UTC, EAbashin commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +import changeAvatar from "../../../public/change-avatar.png";
Причин нет, переделал.

2023-03-12 19:19 UTC, EAbashin commented on packages/client/src/pages/ProfilePage/ProfilePage.module.scss
> +      }
Это я не проверил на тёмном фоне как всё работает. Исправил.

2023-03-12 19:25 UTC, cap-Bernardito approved these changes

2023-03-12 19:25 UTC, cap-Bernardito commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +import { transformUserForRequest } from "../../services/api/transformers";
```
import { transformUserForRequest } from "services/api/transformers";
```

2023-03-12 19:27 UTC, cap-Bernardito commented on packages/client/src/components/app/App.tsx
> +
Интересно... У меня на Win10 работает. Только клиент запускаю. Исследую этот вопрос.

2023-03-13 08:41 UTC, MakhovRoman approved these changes

2023-03-13 17:28 UTC, cap-Bernardito approved these changes

2023-03-13 18:25 UTC, Olegas commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +    },
> Это тип ответа с пользователем, а мы для запроса данные готовим

DTO это Data Transfer Object. Не страшно если он у вас и на вход и на выход если это одно по сути API.

Но если по факту поля разные в этих кейсах, то вариант с UpdateUserRequestData мне нравится больше.

2023-03-13 21:30 UTC, KozlovAleksandr approved these changes

2023-03-14 05:46 UTC, EAbashin commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +    },
Внёс все предложенные.

2023-03-14 05:49 UTC, Olegas approved these changes

2023-03-14 07:55 UTC, cap-Bernardito approved these changes

2023-03-14 16:11 UTC, merged