fix(23UG-22): реализует API для работы с аватаркой
UNOGroup-Practicum/uno-game pull request #30
Opened 2023-03-16 08:10 UTC by EAbashin

### Какую задачу решаем

Даёт возможность добавлять и менять аватарку

2023-03-16 09:26 UTC, cap-Bernardito requested changes

2023-03-16 09:26 UTC, cap-Bernardito commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +      }, 2000);
А зачем всегда сбрасывать ошибку, даже если ее нет?

`await dispatch` мне тут не очень нравится, т.к. противоречит Flux архитектуре. Получается, что мы ждем завершения работы диспатча. Но он же должен просто `thunk` запустить, данные поменяются, и мы должны отреагировать на смену данных.

Т.о. работу с ошибкой в `useEffect` лучше вынести я считаю.

Ну и сейчас баг есть по отображению ошибки. Жмем на аватар, выбираем картинку, аватар меняется, снова жмем на аватар, не выбираем файл (жмем отмена) - ошибка появляется, снова жмем на аватар, снова не выбираем файл, ошибки нет (а должна быть наверное)

Сам процесс смены аватара неочевидный. Обычно есть какие-то кнопки подтверждения. А тут  жму на аватар, условно ради интереса посмотреть, что будет, выбираю или не выбираю файл, и у меня сразу запросы на сервер отправляются или ошибка отображается..., даже если я нажал "Отмена". Очень странный UX.

Может при клике на аватар модалку какую показать с формой загрузки файла? Но тут как народ решит, просто мнение высказал.

2023-03-16 09:26 UTC, cap-Bernardito commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
>      const eventTargetFiles = event.currentTarget.files;
А почему `event.currentTarget`, а не `event.target`? Если я правильно помню, target - это элемент, на котором висит обработчик, он неизменен в процессе всплытия события.  А `currentTarget` - элемент, на котором сработало событие и может меняться.

2023-03-16 09:26 UTC, cap-Bernardito commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +import { useDispatch } from "../../services/hooks";
на 10 строчке такой импорт `import { userSelect, userSlice, userThunks } from "services/slices/user-slice";`
а тремя строками ниже тоже из `services`, но по-другому написан. Давай единнобразно писать без точек.

2023-03-16 16:50 UTC, EAbashin commented on packages/client/src/services/slices/user-slice.ts
> +};
Копи/паст - недосмотрел.

2023-03-16 16:51 UTC, EAbashin commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +      }, 2000);
Не догадался до использования UseEffect. Реализовал сброс ошибки таким способом. Уже переделал.

2023-03-16 16:58 UTC, EAbashin commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +import { useDispatch } from "../../services/hooks";
Автоимпорт подставляет)) Исправил.

2023-03-16 17:46 UTC, cap-Bernardito requested changes

2023-03-16 17:46 UTC, cap-Bernardito commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
>      const eventTargetFiles = event.currentTarget.files;
Моя ошибка, перепутал их.

2023-03-17 14:09 UTC, EAbashin commented on packages/client/src/services/slices/user-slice.ts
> +      dispatch(authSlice.actions.setUser(newUser));
Согласен, переделал.

2023-03-17 14:10 UTC, EAbashin commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +  }, [error]);
Извиняюсь за невнимательность, переделал.

2023-03-17 14:48 UTC, cap-Bernardito approved these changes

2023-03-18 07:14 UTC, Olegas commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
>      }
Совет на будущее. Сейчас у вас обрабатывается количество файлов, и если их больше одного то просто ничего не произойдет и пользователь не поймет где он не прав. Было бы круто либо показать какое-то сообщение (что вы кинули два файла а можно только один или прямо в момент занесения файлов визуально показать что бросать нельзя.

2023-03-18 07:15 UTC, Olegas approved these changes

2023-03-18 09:05 UTC, KozlovAleksandr approved these changes

2023-03-18 09:45 UTC, MakhovRoman approved these changes

2023-03-18 14:13 UTC, EAbashin commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
>      }
В данном случае приложение не позволит выбрать больше одного файла, т.к. не установлен атрибут "multiple"
Пример использования: <input type="file" multiple>
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

2023-03-18 14:27 UTC, merged