feat: реализация страницы 'Правила игры'
UNOGroup-Practicum/uno-game pull request #32
Opened 2023-03-18 09:00 UTC by KozlovAleksandr

### Какую задачу решаем
- реализует страницу "Правила игры"

2023-03-18 09:46 UTC, AleksandrMenshchikov approved these changes

2023-03-18 11:00 UTC, cap-Bernardito requested changes

2023-03-20 19:19 UTC, KozlovAleksandr commented on packages/client/src/pages/RulesPage/RulePageContent.tsx
> +import unoWildCardWild from "../../assets/images-rules/uno-wild-wild.png";
исправлено

2023-03-20 19:19 UTC, KozlovAleksandr commented on packages/client/src/pages/RulesPage/RulePageContent.tsx
> +    </Typography>
исправлено

2023-03-20 19:19 UTC, KozlovAleksandr commented on packages/client/src/pages/RulesPage/RulesPage.module.scss
> +    margin: 0 auto;
исправлено

2023-03-20 19:25 UTC, cap-Bernardito approved these changes

2023-03-20 21:04 UTC, merged