feat(23UG-68): добавляет serviceWorker для production mode
UNOGroup-Practicum/uno-game pull request #33
Opened 2023-03-18 10:44 UTC by cap-Bernardito

### Какую задачу решаем

- добавляет serviceWorker для production mode

2023-03-18 15:23 UTC, EAbashin requested changes

2023-03-18 15:23 UTC, EAbashin commented on packages/client/vite.config.ts
> +      },
Здесь скорее всего тоже надо заменить на /serviceWorker.ts

2023-03-18 15:25 UTC, cap-Bernardito commented on packages/client/vite.config.ts
> +      },
Тут если выше посмотришь, то `serviceWorker.ts` - это энтрипойнт. Он ляжет в `dist/sw.js`.

2023-03-18 15:26 UTC, cap-Bernardito commented on packages/client/src/utils/registerServiceWorker.ts
> +}
Ниже ответил, почему так. А в этом месте указываается файл от корня сайта, который должен подключиться

2023-03-18 16:03 UTC, EAbashin commented
Сначала проверял в dev режиме - увидел, что не работает кеширование и подумал, что дело в неверном названии файла. Но это файл действительно генерируется при сборке и всё работает после команд:
`yarn build --scope=client`
`yarn preview --scope=client`

2023-03-18 16:05 UTC, EAbashin approved these changes

2023-03-19 08:46 UTC, AleksandrMenshchikov approved these changes

2023-03-19 09:25 UTC, Olegas approved these changes

2023-03-19 10:05 UTC, merged