feat(23UG-19): добавляет раздел со сменой пароля
UNOGroup-Practicum/uno-game pull request #36
Opened 2023-03-21 14:44 UTC by MakhovRoman

### Какую задачу решаем

- добавлен раздел со сменой пароля
- добавлена валидация полей

2023-03-21 16:08 UTC, EAbashin commented
Ещё, как вариант, можно вынести в отдельный компонент, сделать в виде модального окна и вызывать его при клике по кнопке. Модальное окно будет просто загораживать контент профиля. В общем, сделать как предложил Алексей, только без роута.
Плюсы такого решения: после смены пароля логично будет возвращаться на страницу профиля и в этом случае не надо будет её отрисовывать заново и отправлять запрос за аватаркой.

2023-03-21 17:08 UTC, cap-Bernardito commented
> Плюсы такого решения: после смены пароля логично будет возвращаться на страницу профиля и в этом случае не надо будет её отрисовывать заново и отправлять запрос за аватаркой.

Но только он не должен возвращаться сразу. Нужно будет дождаться ответа, показать оповещение Ок или не ОК все прошло (т.к. должно быть понятно сменился пароль или нет). Ну и по крестику наверное закрываться... или по таймауту после отображения оповещения.

2023-03-22 11:08 UTC, MakhovRoman commented
Хорошо, я тогда вынесу все в отдельный компонент и модалкой реализую на странице

2023-03-25 04:36 UTC, cap-Bernardito requested changes

2023-03-25 04:36 UTC, cap-Bernardito commented on packages/client/src/components/changePassword/ChangePassword.tsx
> +} from "../../utils/validation/validation";
```ts
import { UpdateUserPassword } from "services/api/types";
import {
  ERROR_MESSAGE,
  InputNames,
  REQUIRED_MESSAGE,
  validationTemplate,
} from "utils/validation/validation";
```

2023-03-25 04:36 UTC, cap-Bernardito commented on packages/client/src/components/changePassword/ChangePassword.module.scss
> +  left: 0;
А зачем верстать свою модалку, когда у нас [библиотека компонентов](https://mui.com/material-ui/react-dialog/) подключена и там полно их?

Ну и если уж на то пошло, то 100% модальное окно должно быть отдельным компонентом, получающим содержимое в качестве чилдренов... А не монолитом с формой. Завтра еще одна форма в модалке понадобится - как ты будешь ее реализовывать?

2023-03-25 04:36 UTC, cap-Bernardito commented on packages/client/src/components/changePassword/ChangePassword.tsx
> +  const updatedUserPassword = {
В качестве названия компонента обычно выбирают существительное.

2023-03-25 04:36 UTC, cap-Bernardito commented on packages/client/src/components/changePassword/ChangePassword.tsx
> +  });
А для чего тут переменная `updatedUserPassword`, если она используется в одном месте сразу после своего объявления?
Почему не написать так?

```ts
  const {
    control,
    handleSubmit,
    formState: { errors, isValid },
  } = useForm({
    defaultValues: {
      oldPassword: "",
      newPassword: "",
      confirmPassword: "",
    },
    mode: "onChange",
  });
```

2023-03-25 04:36 UTC, cap-Bernardito commented on packages/client/src/components/changePassword/ChangePassword.tsx
> +        </form>
У нас во всех формах уведомления о статусе запроса выводятся между полями и кнопкой. Давай так же сделаем, чтобы единообразно было.

2023-03-25 04:36 UTC, cap-Bernardito commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +import { ChangePassword } from "../../components/changePassword/ChangePassword";
`import { ChangePassword } from "components/changePassword/ChangePassword";`

2023-03-25 04:36 UTC, cap-Bernardito commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +
Страницу профиля нужно вернуть в исходный вид. На ней только кнопка вызова модалки должна поменяться.

2023-03-25 04:36 UTC, cap-Bernardito commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
>          </Link>
В "Сменить пароль" не нужны кавычки

2023-03-25 04:36 UTC, cap-Bernardito commented on packages/client/src/services/api/types.ts
> +
С названием опять же беда. Пример названия можно посмотреть выше, можно посмотреть ниже в этом же файле.

2023-03-26 20:41 UTC, KozlovAleksandr approved these changes

2023-03-31 10:58 UTC, cap-Bernardito commented on packages/client/src/components/modal-form/ModalForm.tsx
> +      </DialogContent>
Думаю, имеет смысл вынести `ModalForm` в отдельный компонент и сменить название на `Modal`, т.к. он не имеет никакого отношения к форме (что ему в чилдрены подашь, то и отрисуется)

2023-03-31 10:58 UTC, cap-Bernardito commented on packages/client/src/components/modal-form/password-change-form/PasswordChangeForm.tsx
> +
Если это только для демонстрации, то ок, но вообще так не верно делать. Сам факт отправки пароля не говорит о том, что он успешно изменен. Может прийти сообщение с ошибкой и его надо будет тоже показать в таком случае.
Когда будешь приделывать отправку запроса, учти этот момент. И если ошибка будет, то не должно окно по таймауту закрываться.

2023-03-31 10:58 UTC, cap-Bernardito commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
>        </Container>
Ну, о чем выше и писал - это 2 разные компонента должны быть.

2023-04-03 03:45 UTC, AleksandrMenshchikov approved these changes

2023-04-03 13:37 UTC, EAbashin approved these changes

2023-04-04 04:18 UTC, cap-Bernardito approved these changes

2023-04-04 06:55 UTC, Olegas approved these changes

2023-04-04 10:15 UTC, merged