feat(23-UG20): реализовать API смены пароля
UNOGroup-Practicum/uno-game pull request #47
Opened 2023-04-09 11:28 UTC by MakhovRoman

### Какую задачу решаем

Реализация API смены пароля

2023-04-09 17:20 UTC, cap-Bernardito approved these changes

2023-04-09 20:16 UTC, EAbashin approved these changes
isPasswordSend больше не применяется, поэтому можно удалить создание этой переменной на 51-ой строчке и её изменение на 80-ой.
В остальном всё норм, всё работает)

2023-04-09 20:16 UTC, EAbashin commented on packages/client/src/components/password-change-form/PasswordChangeForm.tsx
> -          Пароль успешно изменен
isPasswordSend больше не применяется, поэтому можно удалить создание этой переменной на 51-ой строчке и её изменение на 80-ой.
В остальном всё норм, всё работает)

2023-04-10 03:02 UTC, AleksandrMenshchikov approved these changes

2023-04-10 04:16 UTC, MakhovRoman commented on packages/client/src/components/password-change-form/PasswordChangeForm.tsx
> -          Пароль успешно изменен
Спасибо, упустил из виду)

2023-04-10 05:40 UTC, Olegas requested changes

2023-04-10 05:40 UTC, Olegas commented on packages/client/src/components/password-change-form/PasswordChangeForm.tsx
> +      setTimeout(() => {
Вот здесь я бы предусмотрел отмену этого таймера на случай, если за 3 секунды пользователь перейдет на какую-то другую страницу.

2023-04-10 05:40 UTC, Olegas commented on packages/client/src/services/slices/user-slice.ts
> +    async (data: PasswordChangeRequest) => await userAPI.changeUserPassword(data)
Не делайте return await - эта конструкция не имеет никакого смысла. Можно смело убрать тут async/await и ничего не изменится

2023-04-10 07:58 UTC, MakhovRoman commented on packages/client/src/components/password-change-form/PasswordChangeForm.tsx
> +      setTimeout(() => {
Добавил отмену таймера и очистку формы

2023-04-10 07:59 UTC, MakhovRoman commented on packages/client/src/services/slices/user-slice.ts
> +    async (data: PasswordChangeRequest) => await userAPI.changeUserPassword(data)
Внес правки

2023-04-10 15:52 UTC, Olegas approved these changes

2023-04-10 20:50 UTC, KozlovAleksandr approved these changes

2023-04-11 04:55 UTC, merged