Feat(23UG-41): добавляет API и серверную часть форума
UNOGroup-Practicum/uno-game pull request #53
Opened 2023-04-29 15:49 UTC by EAbashin

### Какую задачу решаем

- создание и удаление тем форума
- написание сообщений и возможность отвечать на  ранее написаные
- оставление и удаление реакций на сообщения

2023-04-30 06:16 UTC, AleksandrMenshchikov requested changes

2023-04-30 06:16 UTC, AleksandrMenshchikov commented on packages/client/src/pages/ForumPage/ForumMessagesListPage.tsx
При перезагрузке страницы здесь ошибка выходит
TypeError: Cannot destructure property 'user_id' of 'themes.find(...)' as it is undefined.

2023-04-30 15:59 UTC, cap-Bernardito commented on packages/server/routes/forum.ts
> +router.delete("/reactions/:reaction_id", Forum.deleteReaction);
Вот это вот все я могу делать не будучи авторизованным. Мне кажется, что это нехорошо ))
[Пруф](https://disk.yandex.ru/i/OwuKZew5GMaMPg). Сейчас уже реализована возможность получить пользователя и есть пример в `routes/index`. Возможно в этом же PR имеет смысл приделать проверку пользователя.

2023-05-01 08:07 UTC, AleksandrMenshchikov approved these changes

2023-05-01 10:45 UTC, MakhovRoman approved these changes

2023-05-01 11:11 UTC, EAbashin commented on packages/client/src/pages/ForumPage/ForumMessagesListPage.tsx
Вчера до поздней ночи не мог понять происхождение этой ошибки -  точки останова, debagger и console.log почему-то не отрабатывали. Когда попробовал решить с помощью sessionStorage и увидел ошибку: sessionStorage - undefined, понял, что код выполняется в node и вспомнил про SSR.
В общем, ошибка возникала из-за того, что при SSR мы, на тот момент, ещё не делали запрос за всеми темами.

2023-05-01 11:16 UTC, EAbashin commented on packages/server/routes/forum.ts
> +router.delete("/reactions/:reaction_id", Forum.deleteReaction);
Видел твой роут с проверкой авторизации, но почему-то подумал, что он каким-то магическим образом уже работает)))
Спасибо, за наглядное видео и за то, что всё для меня подготовил, подключил эту проверку.

2023-05-02 01:18 UTC, cap-Bernardito commented on packages/client/src/pages/ForumPage/ForumMessagesListPage.tsx
Без SSR была бы та же ошибка, только не на странице выведена, а в консоли, поскольку и на клиенте мы еще не делали запрос за всеми темами. Просто SSR раньше отработал - раньше сломался. Точки останова и прочие прелести не работали, т.к. скрипт не загрузился в браузер - в HTML только ошибка с сервера распечатана.

И по итогу, после приделывания авторизации ошибка сохраняется ))

2023-05-02 01:21 UTC, cap-Bernardito commented on packages/client/src/entry-server.tsx
Тут темы для форму нездорово получать, т.к. они не для всех страниц нужны (а пользователь для всех). Для этой цели ниже добавлена обработка метода `load` для роутов.

2023-05-03 05:29 UTC, cap-Bernardito approved these changes

2023-05-03 18:58 UTC, Olegas requested changes

2023-05-03 18:58 UTC, Olegas commented on packages/client/src/pages/ForumPage/ForumMessagesListPage.tsx
> +            {`Вы действительно хотите удалить эту тему?`}
{``} - лишние. Достаточно просто текста

2023-05-03 18:58 UTC, Olegas commented on packages/client/src/pages/ForumPage/MessageItem/MessageItem.tsx
> +  )[0];
И тут тоже. Сразу внутри сделать [0] а не снаружи

2023-05-03 18:58 UTC, Olegas commented on packages/client/src/pages/ForumPage/MessageItem/MessageItem.tsx
> +      dispatch(forumThunks.postReaction(dataRequest));
Если из реакций есть только like, может сделать action типа likePost() и в него достаточно передать только ид события? Зачем ему например ид темы?

2023-05-04 06:09 UTC, KozlovAleksandr approved these changes

2023-05-04 16:33 UTC, EAbashin commented on packages/client/src/constants.ts
> +    loader: (dispatch) => getThemes(dispatch),
Исправил

2023-05-04 16:35 UTC, EAbashin commented on packages/client/src/pages/ForumPage/ForumMessagesListPage.tsx
> +            {`Вы действительно хотите удалить эту тему?`}
Исправил

2023-05-05 15:40 UTC, EAbashin commented on packages/server/routes/forum.ts
> +router.delete("/reactions/:reaction_id", Forum.deleteReaction);
Извиняюсь, но этот момент не понял..

2023-05-05 15:57 UTC, EAbashin commented on packages/client/src/pages/ForumPage/ForumThemesListPage.tsx
> +      dispatch(forumThunks.postTheme({ user_id: user.id, title }));
Исправил

2023-05-05 16:12 UTC, EAbashin commented on packages/server/controllers/forum.ts
> +};
На фронте:
- если теме не твоя, то не увидишь кнопку удаления.
`{user_id && user?.id === user_id && (
            <IconButton aria-label="delete" color="error" onClick={handleClickOpen}>
                      <DeleteIcon />
            </IconButton>
)}`
- если ещё не оставлял реакцию, то сердечко без фона и при клике на него отправляется запрос на добавление реакции, если уже оставлял, то при клике - удаление реакции.
`const likesCount = useSelector(
    (state) =>
      state.forum.currentReactions.filter(
        (reaction) => reaction.message_id === messageData.id && reaction.reaction === "like"
      ).length
  );
const myLike = useSelector((state) =>
    state.forum.currentReactions.filter(
      (reaction) =>
        reaction.message_id === messageData.id &&
        reaction.reaction === "like" &&
        reaction.user_id === user.id
    )
  )[0];
.....
<IconButton className={styles.MessageItem__like} color="error" onClick={onClickLike}>
          {myLike?.id ? <FavoriteIcon /> : <FavoriteBorderIcon />}
          <Typography variant="subtitle2" ml={1}>
                      {likesCount}
          </Typography>
</IconButton>
`

2023-05-05 16:27 UTC, EAbashin commented on packages/client/src/pages/ForumPage/MessageItem/MessageItem.tsx
> +      dispatch(forumThunks.postReaction(dataRequest));
Да, действительно так можно сделать, тем более поле reaction необязательное и если ничего не придёт, значение по умолчанию будет "like", но так нагляднее и, в то же время, я сделал всё для дальнейшего расширения - можно легко добавить новые флаги в компоненте ("dislike", "fire", "roket"), проверку по ним и вёрстку (бек и BLL можно не трогать).

2023-05-06 05:23 UTC, Olegas commented on packages/server/controllers/forum.ts
> +};
Проверка на фронте это ок, но еще проверка должна быть на стороне бэка, т.к. я могу сформировать запрос к API руками и, если проверки нет, удалить чужую тему.

2023-05-06 05:29 UTC, Olegas commented on packages/client/src/pages/ForumPage/ForumMessagesListPage.tsx
> +    dispatch(forumThunks.postMessage(data));
Про родительский пост. Так это я тогда могу писать ответы на то чего не было (опять же подложить в вызов какой-то свой текст и будет выглядеть как будто это был текст поста, на который я пишу ответ). Плохая история. А где там 20 запросов? Почему нельзя вытянуть все одним запросом? Вроде даже ORM позволяет связанные сущности вытаскивать.

2023-05-07 05:15 UTC, EAbashin commented on packages/server/controllers/forum.ts
> +};
Сделал через createSelector. Протестировал - хорошо работает.

2023-05-07 05:16 UTC, EAbashin commented on packages/client/src/pages/ForumPage/MessageItem/MessageItem.tsx
> +  );
Сделал через createSelector. Протестировал - хорошо работает.

2023-05-07 05:17 UTC, EAbashin commented on packages/client/src/pages/ForumPage/MessageItem/MessageItem.tsx
> +  )[0];
Сделал, надеюсь правильно понял)

2023-05-07 06:50 UTC, Olegas commented on packages/server/routes/forum.ts
> +router.delete("/reactions/:reaction_id", Forum.deleteReaction);
> Что касается второй части вопроса. Возможно речь о том, что сейчас пользователь, для которого создается тема, берется из [`req.body`](https://github.com/UNOGroup-Practicum/uno-game/blob/dev-backend-forum/packages/server/controllers/forum.ts#L50), а должен из пользователя, которого получили с помощью аутентификационной куки. В этом случае в мидлваре нужно сохранить куда-то пользователя и в местах, где он нужен работать с этим сохраненным пользователем.

@cap-Bernardito @EAbashin да, речь именно об этом. Если у вас действие выполняется для авторизованного пользователя, то надо брать это из достоверного источника. Параметры в запросе - не достоверный источник.  Верно - мидлвара должна куда-то в request сохранить данные текущего пользователя и дальше контроллеры должны брать оттуда

2023-05-07 17:12 UTC, EAbashin commented on packages/server/routes/forum.ts
> +router.delete("/reactions/:reaction_id", Forum.deleteReaction);
Понял, спасибо! Изменил.

2023-05-07 17:18 UTC, EAbashin commented on packages/client/src/pages/ForumPage/ForumMessagesListPage.tsx
> +    dispatch(forumThunks.postMessage(data));
Не учёл эту уязвимость и, наверное, уставший был, когда писал про запросы)) У нас же в стейте уже есть все сообщения выбранной темы, надо просто найти нужное по id.
Исправил.

2023-05-07 17:52 UTC, EAbashin commented on packages/server/controllers/forum.ts
> +};
Согласен. Сделал дополнительную проверку на беке.

2023-05-07 17:53 UTC, EAbashin commented
Все замечания исправлены.

2023-05-10 15:44 UTC, Olegas approved these changes

2023-05-10 15:51 UTC, merged