feat(23UG-4): реализует страницу leaderboard
UNOGroup-Practicum/uno-game pull request #7
Opened 2023-02-25 07:46 UTC by KozlovAleksandr

### Какую задачу решаем
- реализует страницу leaderboard

2023-02-25 08:20 UTC, cap-Bernardito reviewed
Все здорово, только немного лишнего кода нашел. Оставил пометки ))

2023-02-25 08:20 UTC, cap-Bernardito commented on packages/client/src/components/leaderboard-profile/LeaderbordProfile.module.scss
> +}
Этот класс ведь не используется в `LeaderbordProfile.tsx`? Если так, то нужно удалить его.

2023-02-25 08:20 UTC, cap-Bernardito commented on packages/client/src/pages/LiderboardPage/LiderboardPage.module.scss
> +
Тут тоже `d-flex` не нужен вроде. Он в загглушках просто так добавлен, т.к. пустое блок оставлять нельзя было (stylelint ругается)

2023-02-25 08:32 UTC, cap-Bernardito commented on packages/client/src/components/leaderboard-profile/LeaderbordProfile.module.scss
> +@import "../../styles/themes/dark";
Импорты выглядят лишними. В этих же файлах нет `scss` переменных

2023-02-25 10:38 UTC, KozlovAleksandr commented on packages/client/src/components/leaderboard-profile/LeaderbordProfile.module.scss
> +}
done

2023-02-25 10:38 UTC, KozlovAleksandr commented on packages/client/src/pages/LiderboardPage/LiderboardPage.module.scss
> +
done

2023-02-25 10:47 UTC, cap-Bernardito approved these changes

2023-02-25 14:00 UTC, AleksandrMenshchikov approved these changes

2023-02-26 08:00 UTC, MakhovRoman approved these changes

2023-02-26 18:03 UTC, EAbashin approved these changes

2023-02-28 06:52 UTC, Olegas requested changes

2023-02-28 06:52 UTC, Olegas commented on packages/client/src/components/leaderboard-profile/LeaderbordProfile.tsx
> +  };
Тип лучше вынести за границы компонента

2023-02-28 06:52 UTC, Olegas commented on packages/client/src/components/leaderboard-profile/LeaderbordProfile.tsx
> +                    console.log(value);
Затесалась отладочная инфа, давайте уберем

2023-02-28 06:52 UTC, Olegas commented on packages/client/src/components/leaderboard-profile/LeaderbordProfile.tsx
> +  const createLabelDisplayedRows = (DisplayedRowsArgs: LabelDisplayedRowsArgs): string => {
Название переменной лучше писать с маленькой буквы, что бы это не путалось с названием типов, классов и т.п.
Также эта функция явно чистая, ее надо вынести за границы компонента что бы не пересоздавать ее каждый рендер.

2023-02-28 06:52 UTC, Olegas commented on packages/client/src/components/leaderboard-profile/LeaderbordProfile.tsx
> +    return `${from}–${to} из ${count !== -1 ? count : `more than ${to}`}`;
Тут странность. Интерфейс на русском, а тут на английском.

2023-02-28 06:52 UTC, Olegas commented on packages/client/src/pages/LiderboardPage/LiderboardPage.tsx
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Для чего здесь отключается линтер?

2023-03-01 10:22 UTC, cap-Bernardito commented on packages/client/src/styles/themes/dark.scss
> +
Эти переменные нужно убрать отсюда и задать стили в файле [muiPallete.tsx](https://github.com/UNOGroup-Practicum/uno-game/blob/dev-page-leaderboard/packages/client/src/theme/muiPallete.tsx)

И, вероятно, вообще имеет смысл избавиться от этих переменных, т.к., судя по названию, они только для таблиц используются. [Тут](https://mui.com/material-ui/customization/default-theme/) палитра цветов для Mui. Цветные цвета лучше использовать `primary`, `secondary`... - из этих групп, оттенки серого - из группы `grey` - тогда более консистентно будет. А если для каждого компонента мы будет вводить свои переменные, то потонем в зоопарке цветов ))

2023-03-01 10:24 UTC, cap-Bernardito commented on packages/client/src/styles/themes/normal.scss
> +}
Написанное выше справедливо и для этого файла. Пока светлую тему не делаем, можно его удалить.

2023-03-02 20:44 UTC, KozlovAleksandr commented on packages/client/src/components/leaderboard-profile/LeaderbordProfile.tsx
> +  };
Исправлено

2023-03-02 20:44 UTC, KozlovAleksandr commented on packages/client/src/components/leaderboard-profile/LeaderbordProfile.tsx
> +                    console.log(value);
Исправлено

2023-03-02 20:44 UTC, KozlovAleksandr commented on packages/client/src/components/leaderboard-profile/LeaderbordProfile.tsx
> +  const createLabelDisplayedRows = (DisplayedRowsArgs: LabelDisplayedRowsArgs): string => {
Исправлено

2023-03-02 20:44 UTC, KozlovAleksandr commented on packages/client/src/components/leaderboard-profile/LeaderbordProfile.tsx
> +    return `${from}–${to} из ${count !== -1 ? count : `more than ${to}`}`;
Исправлено

2023-03-02 20:44 UTC, KozlovAleksandr commented on packages/client/src/pages/LiderboardPage/LiderboardPage.tsx
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Исправлено

2023-03-02 20:44 UTC, KozlovAleksandr commented on packages/client/src/styles/themes/dark.scss
> +
Исправлено

2023-03-03 16:03 UTC, Olegas requested changes

2023-03-03 16:03 UTC, Olegas commented on packages/client/src/components/leaderboard-profile/database.tsx
> +export const Profiles: Profiles[] = [
Тут бы по разному назвать тип и переменную. Список профилей лучше с маленькой буквы назвать.

2023-03-06 18:09 UTC, KozlovAleksandr commented on packages/client/src/components/leaderboard-profile/database.tsx
> +export const Profiles: Profiles[] = [
исправлено

2023-03-08 10:00 UTC, merged